import { Link, Navigate, useParams } from 'react-router-dom';
import HiLogo from '../components/ui/HiLogo';
import { getArticle, healthArticles } from '../seo/articles';

function PublicHeader() {
  return <header className="border-b border-pink-100 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4"><Link to="/" className="flex items-center gap-3"><HiLogo size={40}/><span className="text-lg font-black text-slate-950">HiLover</span></Link><nav aria-label="Điều hướng kiến thức" className="flex items-center gap-4 text-sm font-bold"><Link to="/kien-thuc" className="text-slate-700 hover:text-pink-600">Kiến thức</Link><Link to="/register" className="rounded-xl bg-pink-600 px-4 py-2 text-white">Bắt đầu</Link></nav></div></header>;
}

function PublicFooter() {
  return <footer className="border-t border-pink-100 bg-white"><div className="mx-auto flex max-w-6xl flex-col gap-3 px-4 py-8 text-sm text-slate-600 sm:flex-row sm:items-center sm:justify-between"><p>© 2026 HiLover. Nội dung mang tính tham khảo.</p><div className="flex gap-4 font-bold"><Link to="/kien-thuc/quy-trinh-bien-tap">Quy trình biên tập</Link><Link to="/privacy">Quyền riêng tư</Link><Link to="/help">Trợ giúp</Link></div></div></footer>;
}

export function KnowledgeHubPage() {
  return <div className="min-h-screen bg-[#fffafb] text-slate-800"><PublicHeader/><main><section className="border-b border-pink-100 bg-white"><div className="mx-auto max-w-6xl px-4 py-14 md:py-20"><p className="font-bold text-pink-600">Kiến thức từ HiLover</p><h1 className="mt-3 max-w-3xl text-4xl font-black tracking-[-0.03em] text-slate-950 md:text-5xl">Hiểu cơ thể bằng thông tin rõ ràng, có nguồn</h1><p className="mt-5 max-w-[68ch] text-lg leading-8 text-slate-700">Các bài viết giúp bạn ghi nhận sức khỏe và chuẩn bị câu hỏi tốt hơn khi cần trao đổi với nhân viên y tế. Nội dung không thay thế chẩn đoán hoặc điều trị.</p></div></section><section className="mx-auto max-w-6xl px-4 py-12"><div className="flex flex-wrap gap-3" aria-label="Chủ đề">{Array.from(new Set(healthArticles.map(a=>a.category))).map(category=><span key={category} className="rounded-full bg-pink-50 px-4 py-2 text-sm font-bold text-pink-800">{category}</span>)}</div><div className="mt-8 grid gap-5 md:grid-cols-2">{healthArticles.map(article=><article key={article.slug} className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-pink-100"><p className="text-sm font-bold text-pink-700">{article.category} · {article.readMinutes} phút đọc</p><h2 className="mt-3 text-2xl font-extrabold leading-tight text-slate-950"><Link to={`/kien-thuc/${article.slug}`} className="hover:text-pink-600">{article.title}</Link></h2><p className="mt-3 leading-7 text-slate-700">{article.description}</p><Link to={`/kien-thuc/${article.slug}`} className="mt-5 inline-flex font-bold text-pink-700">Đọc bài viết →</Link></article>)}</div></section></main><PublicFooter/></div>;
}

export function KnowledgeArticlePage() {
  const { slug = '' } = useParams();
  const article = getArticle(slug);
  if (!article) return <Navigate to="/404" replace />;
  return <div className="min-h-screen bg-[#fffafb] text-slate-800"><PublicHeader/><main><article><header className="border-b border-pink-100 bg-white"><div className="mx-auto max-w-4xl px-4 py-12 md:py-16"><nav aria-label="Breadcrumb" className="text-sm font-bold text-slate-600"><Link to="/kien-thuc" className="hover:text-pink-600">Kiến thức</Link><span aria-hidden="true"> / </span><span>{article.category}</span></nav><h1 className="mt-5 text-4xl font-black tracking-[-0.03em] text-slate-950 md:text-5xl">{article.title}</h1><p className="mt-5 max-w-[68ch] text-lg leading-8 text-slate-700">{article.summary}</p><div className="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-sm text-slate-600"><span>{article.author}</span><span>Cập nhật <time dateTime={article.updatedAt}>{article.updatedAt}</time></span><span>{article.readMinutes} phút đọc</span></div></div></header><div className="mx-auto grid max-w-6xl gap-10 px-4 py-12 lg:grid-cols-[240px_minmax(0,720px)]"><aside><div className="sticky top-6 rounded-2xl bg-white p-5 ring-1 ring-pink-100"><p className="font-extrabold text-slate-950">Trong bài viết</p><ol className="mt-3 space-y-2 text-sm leading-6">{article.sections.map(section=><li key={section.id}><a href={`#${section.id}`} className="text-slate-700 hover:text-pink-700">{section.title}</a></li>)}</ol></div></aside><div><div className="rounded-2xl bg-rose-50 p-5 text-sm leading-6 text-rose-950 ring-1 ring-rose-200"><strong>Lưu ý:</strong> Nội dung chỉ nhằm mục đích giáo dục, không thay thế chẩn đoán, tư vấn hoặc điều trị trực tiếp từ nhân viên y tế.</div>{article.sections.map(section=><section key={section.id} id={section.id} className="scroll-mt-6 py-7"><h2 className="text-2xl font-extrabold text-slate-950">{section.title}</h2>{section.paragraphs.map(paragraph=><p key={paragraph} className="mt-4 text-base leading-8 text-slate-700">{paragraph}</p>)}</section>)}<section className="border-t border-pink-100 pt-8"><h2 className="text-2xl font-extrabold text-slate-950">Câu hỏi thường gặp</h2>{article.faqs.map(faq=><details key={faq.question} className="mt-4 rounded-xl bg-white p-5 ring-1 ring-pink-100"><summary className="cursor-pointer font-bold text-slate-950">{faq.question}</summary><p className="mt-3 leading-7 text-slate-700">{faq.answer}</p></details>)}</section><section className="mt-10 border-t border-pink-100 pt-8"><h2 className="text-xl font-extrabold text-slate-950">Nguồn tham khảo</h2><ul className="mt-4 list-disc space-y-2 pl-5">{article.sources.map(source=><li key={source.url}><a href={source.url} target="_blank" rel="noreferrer" className="font-semibold text-pink-700 underline decoration-pink-300 underline-offset-4">{source.label}</a></li>)}</ul><p className="mt-6 text-sm leading-6 text-slate-600">Viết bởi {article.author}. Kiểm tra cấu trúc và nguồn bởi {article.reviewer}. <Link to="/kien-thuc/quy-trinh-bien-tap" className="font-bold text-pink-700">Xem quy trình biên tập.</Link></p></section></div></div></article></main><PublicFooter/></div>;
}

export function EditorialProcessPage() {
  return <div className="min-h-screen bg-[#fffafb] text-slate-800"><PublicHeader/><main className="mx-auto max-w-3xl px-4 py-14"><p className="font-bold text-pink-600">Minh bạch nội dung</p><h1 className="mt-3 text-4xl font-black tracking-[-0.03em] text-slate-950">Quy trình biên tập của HiLover</h1><p className="mt-5 text-lg leading-8 text-slate-700">HiLover xây dựng nội dung để giúp người dùng hiểu và ghi nhận sức khỏe tốt hơn, không nhằm chẩn đoán hoặc thay thế nhân viên y tế.</p>{[['Chọn chủ đề có ích','Ưu tiên câu hỏi liên quan trực tiếp đến việc ghi nhận chu kỳ, triệu chứng và giao tiếp với bạn đời.'],['Kiểm tra nguồn','Mỗi bài sử dụng nguồn từ tổ chức y tế, cơ quan công hoặc hiệp hội chuyên môn có uy tín.'],['Tự duyệt nội bộ','Nhóm sản phẩm kiểm tra cách diễn đạt, phạm vi khuyến nghị, liên kết nguồn và cảnh báo an toàn trước khi xuất bản.'],['Cập nhật và sửa sai','Bài viết hiển thị ngày cập nhật. Phản hồi hoặc yêu cầu sửa nội dung có thể gửi qua Trung tâm trợ giúp.']].map(([title,body])=><section key={title} className="border-b border-pink-100 py-7"><h2 className="text-xl font-extrabold text-slate-950">{title}</h2><p className="mt-3 leading-7 text-slate-700">{body}</p></section>)}<div className="mt-8 rounded-2xl bg-amber-50 p-5 text-sm leading-6 text-amber-950 ring-1 ring-amber-200"><strong>Giới hạn hiện tại:</strong> nội dung đang được nhóm dự án tự duyệt, chưa được một chuyên gia y khoa độc lập duyệt. Vì vậy HiLover giới hạn bài viết ở thông tin giáo dục và luôn dẫn nguồn để người đọc kiểm tra.</div></main><PublicFooter/></div>;
}

export function NotFoundPage() {
  return <div className="flex min-h-screen items-center justify-center bg-[#fffafb] px-4 text-center"><main><p className="text-sm font-bold text-pink-600">Lỗi 404</p><h1 className="mt-3 text-4xl font-black text-slate-950">Không tìm thấy trang</h1><p className="mt-4 text-slate-700">Đường dẫn này không tồn tại hoặc đã được thay đổi.</p><div className="mt-7 flex justify-center gap-3"><Link to="/" className="rounded-xl bg-pink-600 px-5 py-3 font-bold text-white">Về trang chủ</Link><Link to="/kien-thuc" className="rounded-xl bg-white px-5 py-3 font-bold text-slate-800 ring-1 ring-slate-200">Xem kiến thức</Link></div></main></div>;
}
