import { useMemo, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { z } from 'zod';
import { ChatCircleDots, MagnifyingGlass, ShieldCheck } from '@phosphor-icons/react';
import { toast } from 'react-hot-toast';
import Button from '../components/ui/Button';
import HiLogo from '../components/ui/HiLogo';
import api from '../lib/api';
import { getUserFacingError } from '../lib/userFacingError';
import { useAuthStore } from '../store/authStore';
import type { SupportCategory, SupportDetail, SupportPageData, SupportStatus, SupportTicket } from '../types/support';

const faqs = [
  ['Bắt đầu với Hi', 'Đăng ký, hoàn tất onboarding và nhập dữ liệu sức khỏe cần thiết để Hi cá nhân hóa trải nghiệm.'],
  ['Theo dõi chu kỳ', 'Chỉ kỳ kinh đã xác nhận được lưu vào lịch sử. Dự đoán sẽ chính xác hơn khi bạn thêm đủ dữ liệu.'],
  ['Người ấy', 'Hai tài khoản phải chủ động kết nối. Bạn có thể hủy kết nối bất kỳ lúc nào trong cài đặt.'],
  ['Hi AI', 'Hi AI cung cấp thông tin tham khảo và không thay thế chẩn đoán hoặc tư vấn trực tiếp từ bác sĩ.'],
  ['Thanh toán', 'Nếu giao dịch chưa cập nhật, hãy gửi ticket kèm thời gian và mã đơn, không gửi thông tin thẻ hoặc OTP.'],
];
const categoryLabels: Record<SupportCategory,string> = { ACCOUNT:'Tài khoản',PAYMENT:'Thanh toán',TECHNICAL:'Lỗi kỹ thuật',DATA_PRIVACY:'Dữ liệu & quyền riêng tư',OTHER:'Khác' };
const statusLabels: Record<SupportStatus,string> = { OPEN:'Mới',IN_PROGRESS:'Đang xử lý',WAITING_FOR_USER:'Chờ bạn phản hồi',CLOSED:'Đã đóng' };
const schema = z.object({ title:z.string().trim().min(5,'Tiêu đề cần ít nhất 5 ký tự').max(120), category:z.enum(['ACCOUNT','PAYMENT','TECHNICAL','DATA_PRIVACY','OTHER']), message:z.string().trim().min(10,'Nội dung cần ít nhất 10 ký tự').max(2000) });
type FormData=z.infer<typeof schema>;

export default function SupportPage() {
  const token=useAuthStore(s=>s.token); const [params,setParams]=useSearchParams(); const qc=useQueryClient();
  const [search,setSearch]=useState(''); const [status,setStatus]=useState<SupportStatus|''>(''); const selectedId=params.get('ticket');
  const form=useForm<FormData>({resolver:zodResolver(schema),defaultValues:{title:'',category:'TECHNICAL',message:''}});
  const list=useQuery<SupportPageData>({queryKey:['support-tickets',status],queryFn:()=>api.get('/support/tickets',{params:{status:status||undefined}}).then(r=>r.data.data),enabled:!!token});
  const detail=useQuery<SupportDetail>({queryKey:['support-ticket',selectedId],queryFn:()=>api.get(`/support/tickets/${selectedId}`).then(r=>r.data.data),enabled:!!token&&!!selectedId});
  const create=useMutation({mutationFn:(v:FormData)=>api.post('/support/tickets',v).then(r=>r.data.data as SupportDetail),onSuccess:d=>{qc.invalidateQueries({queryKey:['support-tickets']});form.reset();setParams({ticket:d.ticket._id});toast.success('Đã gửi yêu cầu hỗ trợ');},onError:e=>toast.error(getUserFacingError(e))});
  const reply=useMutation({mutationFn:(message:string)=>api.post(`/support/tickets/${selectedId}/messages`,{message}),onSuccess:()=>{qc.invalidateQueries({queryKey:['support-ticket',selectedId]});qc.invalidateQueries({queryKey:['support-tickets']});toast.success('Đã gửi phản hồi');},onError:e=>toast.error(getUserFacingError(e))});
  const reopen=useMutation({mutationFn:()=>api.patch(`/support/tickets/${selectedId}/reopen`),onSuccess:()=>{qc.invalidateQueries({queryKey:['support-ticket',selectedId]});qc.invalidateQueries({queryKey:['support-tickets']});toast.success('Đã mở lại ticket');}});
  const filtered=useMemo(()=>list.data?.items.filter(t=>`${t.ticketCode} ${t.title}`.toLowerCase().includes(search.toLowerCase()))??[],[list.data,search]);
  return <div className="min-h-[100dvh] bg-slate-50 text-slate-800">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4"><Link to={token?'/dashboard':'/'} className="flex items-center gap-3"><HiLogo size={38}/><span className="font-extrabold text-slate-950">Hi Support</span></Link>{token?<Link to="/dashboard" className="text-sm font-bold text-pink-600">Về ứng dụng</Link>:<Link to="/login?next=/help" className="rounded-xl bg-pink-600 px-4 py-2 text-sm font-bold text-white">Đăng nhập</Link>}</div></header>
    <main className="mx-auto max-w-6xl px-4 py-8">
      <section className="mb-8 max-w-3xl"><div className="mb-3 flex items-center gap-2 text-sm font-bold text-pink-600"><ShieldCheck size={20}/>Hỗ trợ riêng tư và an toàn</div><h1 className="text-3xl font-black tracking-tight text-slate-950 md:text-4xl">Chúng tôi có thể giúp gì cho bạn?</h1><p className="mt-3 max-w-[65ch] leading-7 text-slate-600">Tìm câu trả lời nhanh hoặc gửi yêu cầu để đội ngũ Hi hỗ trợ trực tiếp trong ứng dụng.</p></section>
      <section className="mb-10"><div className="relative max-w-xl"><MagnifyingGlass className="absolute left-3 top-3 text-slate-500"/><input value={search} onChange={e=>setSearch(e.target.value)} aria-label="Tìm kiếm trợ giúp" placeholder="Tìm hướng dẫn hoặc ticket" className="w-full rounded-xl border border-slate-300 bg-white py-2.5 pl-10 pr-4 text-sm outline-none focus:border-pink-500 focus:ring-2 focus:ring-pink-100"/></div><div className="mt-5 grid gap-3 md:grid-cols-2">{faqs.filter(([a,b])=>`${a} ${b}`.toLowerCase().includes(search.toLowerCase())).map(([a,b])=><details key={a} className="rounded-xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer font-bold text-slate-900">{a}</summary><p className="mt-3 text-sm leading-6 text-slate-600">{b}</p></details>)}</div></section>
      {!token?<section className="rounded-2xl bg-slate-900 p-6 text-white"><h2 className="text-xl font-extrabold">Cần hỗ trợ riêng cho tài khoản?</h2><p className="mt-2 text-sm leading-6 text-slate-300">Đăng nhập để gửi yêu cầu và theo dõi phản hồi. Bạn cũng có thể liên hệ hilover.space@gmail.com.</p><Link to="/login?next=/help" className="mt-5 inline-flex rounded-xl bg-pink-500 px-5 py-2.5 text-sm font-bold text-white">Đăng nhập để gửi yêu cầu</Link></section>:
      <div className="grid gap-6 lg:grid-cols-[360px_1fr]">
        <aside className="space-y-4"><form onSubmit={form.handleSubmit(v=>create.mutate(v))} className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-extrabold text-slate-950">Tạo yêu cầu mới</h2><p className="mt-1 text-xs leading-5 text-slate-600">Không gửi mật khẩu, OTP hoặc dữ liệu sức khỏe không cần thiết.</p><label className="mt-4 block text-sm font-bold">Tiêu đề<input {...form.register('title')} className="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"/></label>{form.formState.errors.title&&<p className="mt-1 text-xs text-red-600">{form.formState.errors.title.message}</p>}<label className="mt-3 block text-sm font-bold">Danh mục<select {...form.register('category')} className="mt-1.5 w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm">{Object.entries(categoryLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="mt-3 block text-sm font-bold">Nội dung<textarea {...form.register('message')} rows={4} className="mt-1.5 w-full resize-y rounded-xl border border-slate-300 px-3 py-2.5 text-sm"/></label>{form.formState.errors.message&&<p className="mt-1 text-xs text-red-600">{form.formState.errors.message.message}</p>}<Button type="submit" fullWidth loading={create.isPending} className="mt-4">Gửi yêu cầu</Button></form>
          <div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between"><h2 className="font-extrabold">Ticket của bạn</h2><select aria-label="Lọc trạng thái" value={status} onChange={e=>setStatus(e.target.value as SupportStatus|'')} className="rounded-lg border border-slate-300 bg-white px-2 py-1.5 text-xs"><option value="">Tất cả</option>{Object.entries(statusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="mt-3 space-y-2">{list.isLoading?<TicketSkeleton/>:filtered.length===0?<p className="py-6 text-center text-sm text-slate-600">Chưa có ticket phù hợp.</p>:filtered.map(t=><TicketRow key={t._id} ticket={t} active={t._id===selectedId} onClick={()=>setParams({ticket:t._id})}/>)}</div></div>
        </aside>
        <section className="min-h-[480px] rounded-2xl border border-slate-200 bg-white p-5 md:p-6">{!selectedId?<div className="flex min-h-[420px] flex-col items-center justify-center text-center"><ChatCircleDots size={42} className="text-pink-500"/><h2 className="mt-3 font-extrabold text-slate-950">Chọn một ticket để xem trao đổi</h2></div>:detail.isLoading?<TicketSkeleton/>:detail.isError||!detail.data?<p className="text-sm text-red-600">Không tải được ticket.</p>:<Conversation data={detail.data} onReply={m=>reply.mutate(m)} replying={reply.isPending} onReopen={()=>reopen.mutate()} reopening={reopen.isPending}/>}</section>
      </div>}
    </main></div>;
}

function TicketRow({ticket,active,onClick}:{ticket:SupportTicket;active:boolean;onClick:()=>void}) { return <button onClick={onClick} className={`w-full rounded-xl p-3 text-left transition-colors ${active?'bg-pink-50 ring-1 ring-pink-200':'hover:bg-slate-50'}`}><div className="flex justify-between gap-2"><span className="text-xs font-bold text-pink-700">{ticket.ticketCode}</span><span className="text-[11px] font-semibold text-slate-600">{statusLabels[ticket.status]}</span></div><p className="mt-1 truncate text-sm font-bold text-slate-900">{ticket.title}</p></button> }
function Conversation({data,onReply,replying,onReopen,reopening}:{data:SupportDetail;onReply:(m:string)=>void;replying:boolean;onReopen:()=>void;reopening:boolean}) { const [message,setMessage]=useState(''); const closed=data.ticket.status==='CLOSED'; return <div><div className="border-b border-slate-200 pb-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-bold text-pink-700">{data.ticket.ticketCode} · {categoryLabels[data.ticket.category]}</p><h2 className="mt-1 text-xl font-extrabold text-slate-950">{data.ticket.title}</h2></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-700">{statusLabels[data.ticket.status]}</span></div></div><div className="my-5 max-h-[430px] space-y-3 overflow-y-auto" aria-live="polite">{data.messages.map(m=><div key={m._id} className={`flex ${m.actor==='USER'?'justify-end':'justify-start'}`}><div className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm leading-6 ${m.actor==='USER'?'bg-pink-600 text-white':'bg-slate-100 text-slate-800'}`}><p className="mb-1 text-[11px] font-bold opacity-80">{m.actor==='USER'?'Bạn':'Hi Support'}</p><p className="whitespace-pre-wrap">{m.content}</p></div></div>)}</div>{closed?<Button variant="outline" loading={reopening} onClick={onReopen}>Mở lại ticket</Button>:<form onSubmit={e=>{e.preventDefault();if(message.trim().length>=10){onReply(message);setMessage('')}}}><label className="text-sm font-bold">Phản hồi<textarea value={message} onChange={e=>setMessage(e.target.value)} rows={3} maxLength={2000} className="mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"/></label><div className="mt-2 flex items-center justify-between"><span className="text-xs text-slate-500">{message.length}/2000</span><Button type="submit" loading={replying} disabled={message.trim().length<10}>Gửi phản hồi</Button></div></form>}</div> }
function TicketSkeleton(){return <div className="space-y-3 animate-pulse"><div className="h-16 rounded-xl bg-slate-100"/><div className="h-16 rounded-xl bg-slate-100"/><div className="h-16 rounded-xl bg-slate-100"/></div>}
